name: snack_bar_presenter
description: Provide easy and flexible way to show SnackBar. Simple text, undo, and error style are supported.
version: 0.1.3+1
homepage: https://github.com/mono0926/snack_bar_presenter
environment:
  sdk: ">=2.5.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  riverpod: ">=0.8.0 <1.0.0"
  simple_logger: ">=1.7.0 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
